version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - apt-get update
      - echo Installing ChromeDriver
      - wget https://chromedriver.storage.googleapis.com/111.0.5563.64/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip
      - sudo mv chromedriver /usr/bin/chromedriver
 
  build:
    commands:
      - mvn install
 
